package com.xsolla.android.login.social

enum class SocialNetwork(val providerName: String) {
    GOOGLE("google"),
    FACEBOOK("facebook"),
    TWITTER("twitter"),
    NAVER("naver"),
    BAIDU("baidu"),
    AMAZON("amazon"),
    APPLE("apple"),
    BATTLE_NET("battlenet"),
    DISCORD("discord"),
    GITHUB("github"),
    INSTAGRAM("instagram"),
    KAKAO("kakao"),
    MAIL_RU("mailru"),
    MICROSOFT("microsoft"),
    MSN("msn"),
    OK("ok"),
    PARADOX("paradox"),
    PAYPAL("paypal"),
    PSN("psn"),
    QQ("qq"),
    REDDIT("reddit"),
    STEAM("steam"),
    TWITCH("twitch"),
    VIMEO("vimeo"),
    VK("vk"),
    WECHAT("wechat"),
    WEIBO("weibo"),
    YAHOO("yahoo"),
    YANDEX("yandex"),
    YOUTUBE("youtube"),
    XBOX("xbox"),
    PLAYSTATION("playstation");
}